CREATE TABLE records(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    day TEXT NOT NULL,
    open REAL NOT NULL,
    close REAL NOT NULL,
    fund_id INTEGER NOT NULL,
    FOREIGN KEY(fund_id) REFERENCES funds(id) ON DELETE CASCADE
);
