CREATE TABLE funds(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    symbol CHAR(10) NOT NULL,
    name CHAR(50),
    type CHAR(3) NOT NULL,
    available INTEGER DEFAULT 0
);
